name: Recreate Old Astro Runners

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  recreate-old-runners:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install Astronomer CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash -s
      
      - name: Configure Astronomer CLI credentials
        run: |
          # Create astro config directory
          mkdir -p ~/.astro
          
          # Configure astro CLI with API token
          cat > ~/.astro/config.yaml << EOF
          context: astronomer.io
          contexts:
            astronomer.io:
              domain: astronomer.io
              token: ${{ secrets.ASTRONOMER_API_TOKEN }}
              workspace: ${{ secrets.ASTRONOMER_WORKSPACE_ID }}
          EOF
        env:
          ASTRONOMER_API_TOKEN: ${{ secrets.ASTRONOMER_API_TOKEN }}
          ASTRONOMER_WORKSPACE_ID: ${{ secrets.ASTRONOMER_WORKSPACE_ID }}
      
      - name: Set Airflow credentials
        run: |
          echo "AIRFLOW_USERNAME=${{ secrets.AIRFLOW_USERNAME }}" >> $GITHUB_ENV
          echo "AIRFLOW_PASSWORD=${{ secrets.AIRFLOW_PASSWORD }}" >> $GITHUB_ENV
          echo "SLACK_APP_URL=${{ secrets.SLACK_APP_URL }}" >> $GITHUB_ENV
      
      - name: Run recreate old runners script
        run: |
          python scripts/manage_astro_runners.py --recreate-old -y
        env:
          ASTRO_WORKSPACE_ID: ${{ secrets.ASTRONOMER_WORKSPACE_ID }}
          AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
          AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
          SLACK_APP_URL: ${{ secrets.SLACK_APP_URL }}
      
      - name: Send notification on failure
        if: failure()
        run: |
          echo "❌ Failed to recreate old Astro runners. Check the workflow logs for details."
          # You can add Slack/email notification here if desired

